### ISSUE TITLE
Add support for `atomTestRunner`

### ISSUE THREAD

**Issue by wooorm** [Arcanemagus/ci#2]
I just launched [`atom-tap-test-runner`](https://github.com/wooorm/atom-tap-test-runner), but found that actually testing it doesn’t work, mainly, because there’s a check for `./spec` in the `ci` script. An example of the error which is encountered if there’s no `./spec`, can be seen in [this Travis log](https://travis-ci.org/wooorm/atom-tap-test-runner/jobs/149594587#L309).

**Comment by wooorm** [comment]
Whoop, accidentally pressed <kbd>⏎</kbd> 😬 

Now, the previous Atom testing mechanism meant basically all `./spec/**/*.spec.js` files ran in the test, from what I gather, but this new method needs a user-specified command, e.g., `atom --test test.js`, which of course cannot be generalised for all projects supporting `atomTestRunner`.

I can think of two ways to support `atomTestRunner`.

a) Use `npm test` if there are [no specs](https://github.com/Arcanemagus/ci/blob/efbfd359d11ab2a3b356593ce9ef3a886a906e34/build-package.sh#L121);

b) Don’t do anything if there are no specs, and require the user of this project to specify them:

``` yaml
script: curl -s https://raw.githubusercontent.com/Arcanemagus/ci/atomlinter/build-package.sh | sh && npm test
```

P.S. Is this a good place, or should it be moved upstream?

**Comment by Arcanemagus** [comment]
Hmmm, this particular problem doesn't really have anything to do with the whole Node.js v6 mess, so I would probably move it upstream as _everybody_ can benefit from it.

I rather like the option `a` myself, since it will work for current and alternative setups.

**Comment by wooorm** [comment]
I didn’t see anything in the readme on why this project is in fact a fork, and not pulled in the upstream, and, what it actually does? I’m curious!

I prefer b), as it also works exactly the same for current set-ups (minus that failing tests might now give false positives when re-run), and allows any command from doing the actual tests!

**Comment by Arcanemagus** [comment]
From the lack of response to https://github.com/atom/ci/pull/43#issuecomment-232755625, as well as some private conversations it seems there is currently no plans on the official repo to support anything that can't run through the Node.js v0.10.40 bundled with the current version of `apm`. This repository makes the changes outlined in that comment, allowing the system Node.js (v6) to install and run the linters, while letting `apm` install the actual package. Without that workaround you can't use things like `eslint@3` that require newer versions of Node.js to run.

It seems like Atom v1.10 will include an updated `apm` that bundles Node.js v4.4.5 (currently), which will make this whole repository redundant. When that gets released to stable I plan on just switching the repos that were moved over to here back to the official scripts.

**Comment by wooorm** [comment]
OK it’s upstreamed!

**Comment by Arcanemagus** [comment]
Btw, with https://github.com/atom/ci/pull/49 merged, you can simply set `ATOM_LINT_WITH_BUNDLED_NODE` to false in the environment and the scripts will use the system `node` where available now 😉.
